name: dev-pipeline

on:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  actions: read
  contents: read

jobs:
  dev-pipeline:

    name: 'Deploy to Dev'
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up NodeJS LTS
        uses: ./.github/actions/setup-node

      - name: üì• Install dependencies
        shell: bash
        run: npm install

      - name:
          Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: ‚öôÔ∏è Expose yarn config as "$GITHUB_OUTPUT"
        shell: bash
        run: |
          echo ${{ github.ref_name }}

      - name: Linting
        run: npx nx affected -t lint --base=origin/${{ github.ref_name }} --parallel
